/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "set.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
set_value_rpc_1(int key, char *value1, doubles_array V_value2, struct Coord value3, int *clnt_res,  CLIENT *clnt)
{
	set_value_rpc_1_argument arg;
	arg.key = key;
	arg.value1 = value1;
	arg.V_value2 = V_value2;
	arg.value3 = value3;
	return (clnt_call (clnt, set_value_rpc, (xdrproc_t) xdr_set_value_rpc_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
exist_rpc_1(int key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, exist_rpc,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
