/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "set.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_set_value_rpc_1 (set_value_rpc_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (set_value_rpc_1_svc(argp->key, argp->value1, argp->V_value2, argp->value3, result, rqstp));
}

int
_exist_rpc_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (exist_rpc_1_svc(*argp, result, rqstp));
}

static void
tuplas_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		set_value_rpc_1_argument set_value_rpc_1_arg;
		int exist_rpc_1_arg;
	} argument;
	union {
		int set_value_rpc_1_res;
		int exist_rpc_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case set_value_rpc:
		_xdr_argument = (xdrproc_t) xdr_set_value_rpc_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_set_value_rpc_1;
		break;

	case exist_rpc:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_exist_rpc_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!tuplas_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (TUPLAS, PRUEBA);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, TUPLAS, PRUEBA, tuplas_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (TUPLAS, PRUEBA, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, TUPLAS, PRUEBA, tuplas_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (TUPLAS, PRUEBA, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
