/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "set.h"

bool_t
xdr_Coord (XDR *xdrs, Coord *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_doubles_array (XDR *xdrs, doubles_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->doubles_array_val, (u_int *) &objp->doubles_array_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_set_value_rpc_1_argument (XDR *xdrs, set_value_rpc_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, ~0))
		 return FALSE;
	 if (!xdr_doubles_array (xdrs, &objp->V_value2))
		 return FALSE;
	 if (!xdr_Coord (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}
