/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "set.h"
#include "claves.h"

bool_t
set_value_rpc_1_svc(int key, char *value1, doubles_array V_value2, struct Coord value3, int *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	int num = (int) V_value2.doubles_array_len;
    *result = set_value (key, value1, num, V_value2.doubles_array_val, value3);

     return retval;
}

bool_t
exist_rpc_1_svc(int key, int *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;

   *result = exist(key);

	return retval;
}

int
tuplas_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
