/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "set.h"
#include <stdio.h>
#include "claves.h"


int set_value(int key, char *value1, int N_value2, double *V_value2, struct Coord value3)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	int set_value_rpc_1_key = key;
	char *set_value_rpc_1_value1 = value1;
	int set_value_rpc_1_N_value2 = 0;
	doubles_array set_value_rpc_1_V_value2;
    set_value_rpc_1_V_value2.doubles_array_len = N_value2;
    set_value_rpc_1_V_value2.doubles_array_val = V_value2;
	struct Coord set_value_rpc_1_value3 = value3;

     char *host = "localhost";


#ifndef	DEBUG
	clnt = clnt_create (host, TUPLAS, PRUEBA, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = set_value_rpc_1(set_value_rpc_1_key, set_value_rpc_1_value1, set_value_rpc_1_N_value2, set_value_rpc_1_V_value2, set_value_rpc_1_value3, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

        return result_1;
}


int exist(int key)
{
	CLIENT *clnt;
	enum clnt_stat retval_2;
	int result_2;
	int exist_1_key = key;

    char *host = "localhost";

#ifndef	DEBUG
	clnt = clnt_create (host, TUPLAS, PRUEBA, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_2 = exist_rpc_1(exist_1_key, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

        return result_2;
}


int main (int argc, char *argv[])
{
	double vector[] = {2.3, 3.4};

 	struct Coord ejem;
    ejem.x = 100;
    ejem.y=0;

	int result = set_value(2, "hola", 2, vector, ejem );

    printf("El resultado de la función es: %d\n", result);

    result = exist(2);

    printf("El resultado de la función es: %d\n", result);


	return 0;
}